### ISSUE TITLE
Prepare Backend

### ISSUE THREAD

**Issue by moinferdi** [coding-bootcamps-eu/suryia#3]
- [x] nodemon for dev env
- [x] typescript
- [x] express
- [x] dotenv 
- [x] cors
- [x] bodyparser
- [x] Cors: It should be possible to use the api in the frontend without cors problems
- [x] Port should be set in .env file
- [x] .env must be part of the gitignore
- [x] Write documentation how to getting started.

**Comment by joegregory-cbe** [comment]
Zurück in Progress da nicht fertig
