### ISSUE TITLE
Add Mongo DB to api

### ISSUE THREAD

**Issue by moinferdi** [coding-bootcamps-eu/suryia#7]
- [x] Add mongoose ORM
- [x] Getting started guide
  - [x] How to install MongoDB locally
  - [x] How to set DB Config
  - [ ] How to use fake data (idea migrations and seeders)
- [x] Create an api route with the path `/status`
  - [x] Return the status of the mongo db connection
  - [x] Store the api version in the mongo db
  ```
  {
     status: {
        db: true 
     },
     api_version: 1.5.5 
  }
  ```

**Comment by joegregory-cbe** [comment]
We will solve this task with this issue [How to use fake data (idea migrations and seeders)](https://github.com/orgs/coding-bootcamps-eu/projects/8/views/1?pane=issue&itemId=38037159)
